help:      ## Show this help.
		@grep -h "##" $(MAKEFILE_LIST) 

catalogue: 	## Install catalogue
		@bash components/catalogue.sh

mongodb:	## Install MongoDB
		@bash components/mongodb.sh

redis:		## Install Redis
		@bash components/redis.sh

user:		## Install user
		@bash components/user.sh

cart:		## Install cart
		@bash components/cart.sh

mysql:		## Install MySQL
		@bash components/mysql.sh

shipping:	## Install shipping
		@bash components/shipping.sh

rabbitmq:	## Install rabbitmq
		@bash components/rabbitmq.sh

payment:	## Install Payment
		@bash components/payment.sh

frontend:	## Install Frontend
		@bash components/frontend.sh
										
				
				
				
