help:      ## Show this help.
		@grep -h "##" $(MAKEFILE_LIST) 

catalogue: ## Installing catalogue
		@bash components/catalogue.sh

mongodb:	## Installing MongoDB
		@bash components/mongodb.sh

redis:	## Installing Redis
		@bash components/redis.sh

user:	## Installing user
		@bash components/user.sh

cart:	## Installing cart
		@bash components/cart.sh

mysql:	## Installing MySQL
		@bash components/mysql.sh

shipping:	## Installing shipping
		@bash components/shipping.sh

rabbitmq:	## Installing rabbitmq
		@bash components/rabbitmq.sh

payment:	## Installing Payment
		@bash components/payment.sh

frontend:	## Installing Frontend
		@bash components/frontend.sh
										
				
				
				
